version: 1.0.{build}
image: Visual Studio 2017 Preview
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
build_script:
  - dotnet build -c Release
test_script:

		# Get xUnit Runner Console
    - ps: nuget install xunit.runner.console -OutputDirectory packages -Version 2.3.1

		# Install OpenCover and extract it to ./packages/
    - ps: nuget install OpenCover -OutputDirectory packages -Version 4.6.519

		# Install Coveralls Net and extract it to ./tools/
    - ps: dotnet tool install coveralls.net --version 1.0.0 --tool-path tools

		# Run OpenCover Console
    - ps: > 
			.\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" 
			"-targetargs:"".\packages\xunit.runner.console.2.3.1\tools\netcoreapp2.0\xunit.console.dll"" 
			""MachinesBot.xUnit.Tests\bin\Release\netcoreapp2.0\MachinesBot.xUnit.Tests.dll"" -noshadow -appveyor"
			-filter:"+[MachinesBot*]* -[MachinesBot*]*Tests.*" -oldStyle -output:opencoverCoverage.xml
    
    - ps: > 
			$coveralls = ".\tools\csmacnz.coveralls.exe" 
			$coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN
			--commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH 
			--commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL
			--commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
      